### ISSUE TITLE
Domain expiration

### ISSUE THREAD

**Issue by mkchandler** [bigwhoop/nbachampionshipbelt#7]
I noticed the domain expired for nbachampionshipbelt.com. Any plans to keep it going somewhere else?

**Comment by bigwhoop** [comment]
Nah, not really. Interest wasn't high after the initial year. Feel free to grab the domain and keep it running though ... :+1:

**Comment by mkchandler** [comment]
I'll think about it. I should probably focus on my [NBA Scoring Belt](https://github.com/mkchandler/nbascoringbelt) project (which was inspired by this) and get it stable first though :smile:
